package core.LanguageProcessors.LexerComponents;

public enum TokenType {
    NUMBER_LITERAL,STRING_LITERAL,ARITHEMATIC_OPERATORS,EQUALS,KEYWORD,IDENTIFIER,
    OPEN_PARENS,CLOSED_PARENS,OPEN_BOX_BRACK,CLOSE_BOX_BRACK,OPEN_CURLY_BRACK,
    CLOSE_CURLY_BRACK,END,COMMA,DOUBLE_QUOTES,SINGLE_QUOTES,NOT,DOT,ADD_EQUALS,
    SUB_EQUALS,MUL_EQUALS,DIV_EQUALS,DOUBLE_EQUALS,NOT_EQUALS,AND,OR,INCREMENT,
    DECREMENT,NULL,IF,ELSE,WHILE,FOR,CLASS,STATIC,INT,STRING,CHAR,LONG,BYTE,FLOAT,DOUBLE,
    FINAL,CASE,SWITCH,PRINT,INPUT,VAR,PUBLIC,PRIVATE,RETURN,THIS,TRUE,FALSE,SUPER, CATCH, TRY, DO
}
